# Generated by Django 4.2.23 on 2025-08-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_state_alter_article_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sitemap_max_articles",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="设置网站地图中最多显示的文章数量",
                        verbose_name="网站地图最大文章数量",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "网站配置",
                "verbose_name_plural": "网站配置",
            },
        ),
        migrations.AddField(
            model_name="site_information",
            name="for_the_record",
            field=models.CharField(blank=True, max_length=30, verbose_name="备案号"),
        ),
    ]
