# Generated by Django 4.2.23 on 2025-08-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0002_article_state_alter_article_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="quark_ck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ck",
                    models.CharField(
                        help_text="请输入ck", max_length=2000, verbose_name="ck"
                    ),
                ),
                (
                    "fid",
                    models.CharField(
                        default="default_fid_value",
                        help_text="请输入fid",
                        max_length=100,
                        verbose_name="fid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="quark_NetworkDisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="请输入链接", max_length=2000, verbose_name="链接"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="资源添加的日期和时间",
                        verbose_name="添加时间",
                    ),
                ),
                (
                    "name_fid",
                    models.CharField(
                        help_text="请输入文件名id", max_length=100, verbose_name="文件名id"
                    ),
                ),
                (
                    "network_id",
                    models.ForeignKey(
                        help_text="请选择网络硬盘资源",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.article",
                        verbose_name="网络硬盘资源",
                    ),
                ),
            ],
        ),
    ]
