# Generated by Django 4.2.23 on 2025-08-14 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article_tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20, verbose_name="标签")),
            ],
            options={
                "verbose_name": "文章标签",
                "verbose_name_plural": "文章标签",
            },
        ),
        migrations.CreateModel(
            name="Article_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="分类")),
                (
                    "Font_Awesome_Web",
                    models.CharField(default="None", max_length=20, verbose_name="图标"),
                ),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
            },
        ),
        migrations.CreateModel(
            name="Downloads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Weekly_Downloads",
                    models.IntegerField(default=0, verbose_name="周下载量"),
                ),
                (
                    "Total_Downloads",
                    models.IntegerField(default=0, verbose_name="总下载量"),
                ),
                ("last_reset", models.DateField(auto_now=True, verbose_name="上次重置时间")),
            ],
            options={
                "verbose_name": "下载量统计",
                "verbose_name_plural": "下载量统计",
            },
        ),
        migrations.CreateModel(
            name="Friendship_Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="网站名称")),
                ("url", models.CharField(max_length=200, verbose_name="网站链接")),
            ],
            options={
                "verbose_name": "友情链接",
                "verbose_name_plural": "友情链接",
            },
        ),
        migrations.CreateModel(
            name="Site_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("Site_title", models.CharField(max_length=100, verbose_name="网站标题")),
                (
                    "Site_title_wei",
                    models.CharField(blank=True, max_length=100, verbose_name="副标题"),
                ),
                ("description", models.TextField(blank=True, verbose_name="网站描述")),
                (
                    "keywords",
                    models.CharField(blank=True, max_length=200, verbose_name="关键词"),
                ),
                ("analytics_code", models.TextField(blank=True, verbose_name="分析代码")),
                ("footer_content", models.TextField(blank=True, verbose_name="页脚内容")),
            ],
            options={
                "verbose_name": "网站信息",
                "verbose_name_plural": "网站信息",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                ("view_count", models.IntegerField(default=0, verbose_name="阅读量")),
                (
                    "Create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "Update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("link", models.CharField(max_length=200, verbose_name="网盘链接")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="article.article_tag", verbose_name="标签"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.article_type",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
    ]
