# Generated by Django 4.2.23 on 2025-08-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="state",
            field=models.BooleanField(default=True, verbose_name="网盘状态"),
        ),
        migrations.AlterField(
            model_name="article",
            name="link",
            field=models.CharField(max_length=200, verbose_name="夸克网盘链接"),
        ),
    ]
