# Generated by Django 4.2.23 on 2025-08-28 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_siteconfig_site_information_for_the_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteconfig",
            options={"verbose_name": "网站地图配置", "verbose_name_plural": "网站地图配置"},
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="site_domain",
            field=models.CharField(
                default="https://example.com",
                help_text="用于生成sitemap的完整域名，例如: https://yourdomain.com",
                max_length=200,
                validators=[django.core.validators.URLValidator()],
                verbose_name="网站域名",
            ),
        ),
    ]
