# Generated by Django 4.2.23 on 2025-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpiderVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "visit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
                (
                    "search_engine",
                    models.CharField(
                        choices=[
                            ("baidu", "百度"),
                            ("google", "谷歌"),
                            ("bing", "必应"),
                            ("sogou", "搜狗"),
                            ("360", "360搜索"),
                            ("yandex", "Yandex"),
                            ("duckduckgo", "DuckDuckGo"),
                            ("other", "其他爬虫"),
                        ],
                        max_length=20,
                        verbose_name="搜索引擎",
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="访问路径")),
                (
                    "referer",
                    models.URLField(blank=True, null=True, verbose_name="来源页面"),
                ),
            ],
            options={
                "verbose_name": "爬虫访问记录",
                "verbose_name_plural": "爬虫访问记录",
                "ordering": ["-visit_time"],
            },
        ),
    ]
